-- Nazel Video Downloader
-------------------------------------
--
-- File generated with SQLiteStudio v3.1.1 on Fri Jun 9 23:31:08 2017
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: items
CREATE TABLE items (
    id                    INTEGER PRIMARY KEY
                                  NOT NULL,
    url                   TEXT    NOT NULL,
    location              TEXT    NOT NULL,
    title                 TEXT    NOT NULL,
    customName            TEXT    NOT NULL,
    speedLimit            INTEGER NOT NULL,
    addToQueue            BOOLEAN NOT NULL,
    isVideo               BOOLEAN NOT NULL,
    format                TEXT    NOT NULL,
    videoQuality          INTEGER NOT NULL,
    audioQuality          INTEGER NOT NULL,
    subtitleLanguage      TEXT    NOT NULL,
    embeddedSubtitle      BOOLEAN NOT NULL,
    autoGeneratedSubtitle BOOLEAN NOT NULL,
    isPlaylist            BOOLEAN NOT NULL,
    startIndex            INTEGER,
    endIndex              INTEGER,
    items                 TEXT,
    allItems              BOOLEAN NOT NULL,
    done                  DECIMAL,
    size                  DECIMAL,
    sizeUnit              TEXT
);


COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
